
- name: Install epel
  package:
    name: epel-release
    state: present

- name: Install memcached
  package:
    name: memcached
    state: present

- name: Copy memcached config
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached
    owner: root
    group: root
    mode: '0644'
  notify: restart memcached

- name: Enable & start memcached
  systemd:
    name: memcached
    enabled: yes
    state: started

- name: open port 11211
  ansible.posix.firewalld:
    zone: public
    port: 11211/tcp
    permanent: true
    state: enabled
    immediate: yes
  notify: restart firewalld
